### ISSUE TITLE
Request: Test Beep Button

### ISSUE THREAD

**Issue by Ruthalas** [techfreek/OctoPrint-Friendlybeeper#1]
Would it be possible to add a button to the plugin config page to test the beep?

That would be great to confirm it works prior to running a print, and get an idea for the volume, etc.

Thanks for this! It's a great, simple idea.

**Comment by techfreek** [comment]
I can look into that

**Comment by KenLucke** [comment]
I agree, we need a test button.  Not many people can identify what a beep is going to sound like from a duration and frequency setting :)

**Comment by techfreek** [comment]
I now have this in my development branch, just haven't had time to test it yet

**Comment by Gottox** [comment]
I'm currently working on such a feature. As I'm not into knockout.js there are a few bugs with data bindings but I hope to get something working soon.

**Comment by Gottox** [comment]
Just had a look into your dev branch and you actually got the the part right that I was missing. I'll open a pr later, as I think that you could benefit from my approach.

**Comment by techfreek** [comment]
I was actually prepping to publish my implementation soon. Out of curiosity, what's different about your approach? If it makes sense, I can delay the next release until that makes it in

**Comment by Gottox** [comment]
I added two Testbuttons, one to play in the browser, one to play on the device.

**Comment by techfreek** [comment]
I think the second test button would make sense with #7. I'm not sure what would be gained from playing the sound in the browser if the plugin doesn't have any other support for playing in the browser. Feel free to give an example of how I'm wrong and I'll consider taking for 0.4.0

**Comment by Gottox** [comment]
My idea was to give a rough preview even if I'm using octoprint remotely.

**Comment by techfreek** [comment]
Ahhh gotcha. I get that, I still think that's best combined with #7 since that deals with notifications in the browser. I'm hesitant to do this before then because it would give unrealistic expectations of functionality.
