### ISSUE TITLE
time doesnt match actual time

### ISSUE THREAD

**Issue by Slayforfun** [techfreek/OctoPrint-Friendlybeeper#2]
The time of the plugin states 2 hours before my actual time, which may be a result of summer time for instance, I am certain however that i dont have to resync my windows clock, since that is the same as my other devices.

Would it be possible to include a button which resyncs the time on the PI?

**Comment by techfreek** [comment]
I considered that, but doing so might require running raspi-config (I had to do that) to fix the timezone, which requires root.

I can at least clarify the string implies your octoprint host, maybe even show the configured timezone in case that is the issue. 

I'll try to look closer

**Comment by Slayforfun** [comment]
Requiring root access is probably not what people would be interested in. I definitely like the little clarification though!

**Comment by techfreek** [comment]
This was clarified in the latest update. If it needs further clarification, please let me know

**Comment by davide70** [comment]
Installed the plugin this morning. On my octopi the current time is not updated. At the moment, it's 5 hours and 52 minutes behind. It takes the time at startup and doesn't move until the next restart.

**Comment by techfreek** [comment]
I'm really only able to fetch the time when you load the settings page. I don't really have a way to keep that in sync. At least not sanely/easily.

Further, plugins aren't able to change system time. That would require root/admin privileges, and not even octoprint runs with that. So I'm limited to just showing what's configured and give pointers on how to fix it. Wish I could do more. Sorry
