### ISSUE TITLE
Request: Beep when pause (M0)

### ISSUE THREAD

**Issue by trialkornel66** [techfreek/OctoPrint-Friendlybeeper#4]
Thank You this useful plugin, but I often print multicolor whit one extruder. So that would be very helpful to me, if the printer beeping when come the filament change (M0 in Cura Pause at height).
Thank You very much if You could take this in the plugin.

**Comment by coliss86** [comment]
You could try using [M600](https://marlinfw.org/docs/gcode/M600.html) instead of M0 if you firmware support it. It enables a filament load / unload procedure with beep while waiting for the user.

**Comment by techfreek** [comment]
Looking into it, if the gcode is listed under `pausingCommands` here: http://docs.octoprint.org/en/master/configuration/config_yaml.html#serial

It will cause the print job to pause, which is the likely the closest I could get to detecting `M0`

**Comment by techfreek** [comment]
Added to most recent update. Will require some extra config, but it is configurable
