### ISSUE TITLE
add custom melody ))

### ISSUE THREAD

**Issue by ssavickiy** [techfreek/OctoPrint-Friendlybeeper#6]
; Mortal Combat Theme
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S784 P240
G4 P24
M300 S1046 P240
G4 P24
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S784 P240
G4 P24
M300 S658 P240
G4 P24
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S784 P240
G4 P24
M300 S1046 P240
G4 P24
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S880 P360
G4 P36
M300 S880 P120
G4 P120
M300 S880 P120
G4 P90
M300 S880 P120
G4 P120
M300 S880 P120

**Comment by techfreek** [comment]
I now have this in my development branch, just haven't had time to test it yet
