### ISSUE TITLE
document hardware requirements

### ISSUE THREAD

**Issue by aerickson** [techfreek/OctoPrint-Friendlybeeper#8]
I'd love to add one to my OctoPrint host, but what's required?

Thanks! :)

**Comment by techfreek** [comment]
I can do that, but for now, as long as your printer supports the M300 gcode, it will work: https://reprap.org/wiki/G-code#M300:_Play_beep_sound

So if you have a Marlin, RepRap, Repetier, Prusa, Mk4duo, makerbot, machinekit firmware it will likely work

**Comment by aerickson** [comment]
Aaah saying it uses M300 is enough.

Unfortunately my board doesn't have a beeper attached.

Thanks,
Andy
